server:
  port: 8080
spring:
  datasource:
    #驱动类名称
    driverClassName: com.mysql.cj.jdbc.Driver
    #数据库连接的url
    url: jdbc:mysql://localhost:3306/work5
    #连接数据库的用户名
    username: root
    #连接数据库的密码
    password: 04512htf
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true